# Key settings (must edit)
project_title: Python Checklist 2023
project_repo: lucydot/Python-Northumbria-2023
admins:
- lucydot
instructors:
- lucydot
- r-pallister

students:
- lucydot
- r-pallister

web_address: https://lucydot.github.io/Python-Northumbria-2023

# User options (may edit)
questions: true
votes_required: 4
gh-pages: true
gh-pages_branch: gh-pages
