# Key settings (must edit)
project_title: Python programming at Northumbria
project_repo: lucydot/Python-Northumbria-2023
admins:
- lucydot
- choochoo-bot
instructors:
- lucydot
students:
- lucydot
- choochoo-bot
web_address: https://lucydot.github.io/Python-Northumbria-2023

# User options (may edit)
questions: true
votes_required: 3
gh-pages: true
gh-pages_branch: gh-pages



